name = "ringo-web"
pages_build_output_dir = "./dist"

[[services]]
# ソースコードの中で参照する名前
# hono的には c.env.RINGO_DB_WORKER のように参照する
binding = "RINGO_DB_WORKER"

# serviceは app-workerのwrangler.tomlにある `name` と同じ名前にする必要がある
service = "ringo-db"

# Workersでexportされたクラス名を設定
entrypoint = "DatabaseWorkerEntrypoint"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"