name = "ringo-web"
pages_build_output_dir = "./dist"
compatibility_date = "2024-06-18"

[[services]]
# ソースコードの中で参照する名前
# hono的には c.env.RINGO_DB_WORKER のように参照する
binding = "RINGO_DB_WORKER"

# serviceは app-workerのwrangler.tomlにある `name` と同じ名前にする必要がある
service = "ringo-db"

# Workersでexportされたクラス名を設定
entrypoint = "DatabaseWorkerEntrypoint"