/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonthRouteImport } from './routes/month'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenealogiesIndexRouteImport } from './routes/genealogies/index'
import { Route as GenealogiesAppleNameRouteImport } from './routes/genealogies/$appleName'

const MonthRoute = MonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenealogiesIndexRoute = GenealogiesIndexRouteImport.update({
  id: '/genealogies/',
  path: '/genealogies/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenealogiesAppleNameRoute = GenealogiesAppleNameRouteImport.update({
  id: '/genealogies/$appleName',
  path: '/genealogies/$appleName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/month': typeof MonthRoute
  '/genealogies/$appleName': typeof GenealogiesAppleNameRoute
  '/genealogies/': typeof GenealogiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/month': typeof MonthRoute
  '/genealogies/$appleName': typeof GenealogiesAppleNameRoute
  '/genealogies': typeof GenealogiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/month': typeof MonthRoute
  '/genealogies/$appleName': typeof GenealogiesAppleNameRoute
  '/genealogies/': typeof GenealogiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/month' | '/genealogies/$appleName' | '/genealogies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/month' | '/genealogies/$appleName' | '/genealogies'
  id: '__root__' | '/' | '/month' | '/genealogies/$appleName' | '/genealogies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MonthRoute: typeof MonthRoute
  GenealogiesAppleNameRoute: typeof GenealogiesAppleNameRoute
  GenealogiesIndexRoute: typeof GenealogiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genealogies/': {
      id: '/genealogies/'
      path: '/genealogies'
      fullPath: '/genealogies/'
      preLoaderRoute: typeof GenealogiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genealogies/$appleName': {
      id: '/genealogies/$appleName'
      path: '/genealogies/$appleName'
      fullPath: '/genealogies/$appleName'
      preLoaderRoute: typeof GenealogiesAppleNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MonthRoute: MonthRoute,
  GenealogiesAppleNameRoute: GenealogiesAppleNameRoute,
  GenealogiesIndexRoute: GenealogiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
