/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MonthImport } from './routes/month'
import { Route as IndexImport } from './routes/index'
import { Route as GenealogiesIndexImport } from './routes/genealogies/index'
import { Route as GenealogiesAppleNameImport } from './routes/genealogies/$appleName'

// Create/Update Routes

const MonthRoute = MonthImport.update({
  path: '/month',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GenealogiesIndexRoute = GenealogiesIndexImport.update({
  path: '/genealogies/',
  getParentRoute: () => rootRoute,
} as any)

const GenealogiesAppleNameRoute = GenealogiesAppleNameImport.update({
  path: '/genealogies/$appleName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthImport
      parentRoute: typeof rootRoute
    }
    '/genealogies/$appleName': {
      id: '/genealogies/$appleName'
      path: '/genealogies/$appleName'
      fullPath: '/genealogies/$appleName'
      preLoaderRoute: typeof GenealogiesAppleNameImport
      parentRoute: typeof rootRoute
    }
    '/genealogies/': {
      id: '/genealogies/'
      path: '/genealogies'
      fullPath: '/genealogies'
      preLoaderRoute: typeof GenealogiesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  MonthRoute,
  GenealogiesAppleNameRoute,
  GenealogiesIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/month",
        "/genealogies/$appleName",
        "/genealogies/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/month": {
      "filePath": "month.tsx"
    },
    "/genealogies/$appleName": {
      "filePath": "genealogies/$appleName.tsx"
    },
    "/genealogies/": {
      "filePath": "genealogies/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
